version: '3.9'

services:
  qnode0_app:
    image: smartquail/qnode0_app:latest
    environment:
      - PORT=8020
    env_file:
      - .env 
    depends_on:
      - smartquaildb
    ports:
      - "8001:8020"
    volumes:
      - static-data-qnode0:/vol/web
   # command: sh -c "chmod +x /scripts/migrations.sh && sh /scripts/migrations.sh && sh /scripts/run.sh"

  smartquaildb:
    image: postgres:13-alpine
    restart: always
    command: -p 5432
    env_file:
      - .env 
    ports:
      - "5432:5432"
    env_file:
      - .env 
    expose:
     - 5432
    volumes:
      - smartquaildb_data:/var/lib/postgresql/data/

  qnode01_proxy:
    image: nginx:stable-alpine
    restart: always
    depends_on: 
      - qnode01_app
    ports:
      - "80:8020"
    volumes: 
      - static-data-qnode0:/vol/static

  redis:
    image: redis:3.0
    restart: always
    expose:
      - 6388
    ports:
      - "6388:6388"
    volumes:
      - redis_data:/data
    entrypoint: redis-server --appendonly yes --port 6380

volumes:
  smartquaildb_data:
  redis_data:
  static-data-qnode0: