# Generated by Django 3.2.13 on 2022-05-11 06:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0007_add_autocreate_fields'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('webapp_0', '0002_auto_20220511_0448'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='publicidad',
            new_name='Advertising',
        ),
        migrations.RenameModel(
            old_name='consultas_publicidad',
            new_name='consultas_advertising',
        ),
    ]
