# Generated by Django 3.2.15 on 2022-09-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_0', '0004_auto_20220916_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='behance',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
