name: SmartQuail Docker Build Apps

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
 
jobs:
  test_qnode01_app:
    uses: smartquailDev/qnode0.1_app/.github/workflows/test-qnode0_app.yaml@main
  Docker_qnode01:
    runs-on: ubuntu-latest
    needs: [test_qnode01_app]
    env:
      DJANGO_SECRET_KEY: test-key-not-good
    steps:
    - name: Checkout code
      uses: actions/checkout@v3 
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./qnode01_k8s
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/qnode01_app:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5}
   

       

   
