name: SmartQuail Django-app & Postgress Test

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
 
jobs:
  test_qnode01_app:
     uses: smartquailDev/qnode0.1_app/.github/workflows/test-qnode0_app.yaml@main
  Docker_qnode01:
    runs-on: ubuntu-latest
    needs: [test_qnode01_app]
    env:
      DJANGO_SECRET_KEY: test-key-not-good
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install doctl
      usese: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_API_TOKEN_KEY }}
    - name: Login to Do Container Registry with short-lived creds
      run: dotcl registry login --expiry-seconds 1200
    - name: Build container image
      working-directory: ./qnode0.1_k8s
      run: | 
        docker build -f Dockerfile \ 
           -t registry.digitalocean.com/smartquail/qnode01_app:latest \
           -t registry.digitalocean.com/smartquail/anode01_app:${GITHUB_SHA:: 7} \ .
    - name: Push Image
      run: | 
        docker push registry.digitalocean.com/smartquail/qnode01_app --all-tags

   
